### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by n4tur3502** [fnord12/script.pseudotv#31]
I installed the addon in leia 18.9. When i attempt to load for the first time it gives an error. I checked the log and the only thing i can see for the addon says this 
 EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (Overlay.py, line 172)
                                            Traceback (most recent call last):
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\default.py", line 58, in <module>
                                                Start()
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\default.py", line 49, in Start
                                                import Overlay as Overlay
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\Overlay.py", line 172
                                                >>>>>>> Updated upstream
                                                 ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--

I removed it and reinstalled the steveb version and it loads right up. I did a clean install of your version and no matter what it always gives the same error.

**Comment by fnord12** [comment]
That message you are seeing ">>>>>>> Updated upstream" is something that Github displays when doing a version comparison.  Is it possible that with the way you are bringing down these files, you're accidentally copying that message?

(It's also possible that the message is something that I accidentally left in when doing an update, but I can't find it, definitely not on the two files listed in the error message.)

**Comment by n4tur3502** [comment]
I just went to the main code screen on github and downloaded a zip and installed that to kodi. should i be doing it some other way?

**Comment by fnord12** [comment]
No that's the best way to do it.  It WAS on my end, in a file not listed in the error message (!!) but I've fixed it.  Let me know if you run into any more trouble.

**Comment by n4tur3502** [comment]
Still getting an error. Although it seems a bit different this time?
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (EPGWindow.py, line 660)
                                            Traceback (most recent call last):
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\default.py", line 58, in <module>
                                                Start()
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\default.py", line 49, in Start
                                                import Overlay as Overlay
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\Overlay.py", line 33, in <module>
                                                from EPGWindow import EPGWindow
                                              File "C:\Users\Eric\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\EPGWindow.py", line 660
                                                >>>>>>> Stashed changes
                                                 ^

Edit: I removed that line from the EPGWindow.py file and it seems to work ok now.

**Comment by fnord12** [comment]
Sorry, looks like my last update got mangled! Your fix will prevent the error, but if you want the latest update, which allows you to use the Page Up and Page Down buttons in the EPG, grab the zip file one last time for my latest fix.

**Comment by n4tur3502** [comment]
That did it! Thank you so much!
